### ISSUE TITLE
Can not find the file of sample_funcom_gpt.py

### ISSUE THREAD

**Issue by ying-hit** [apcl-research/Jam-CGPT#2]
When I am going to make an inference with your models.  I can not find the file of sample_funcom_gpt.py. Can you please provide the file of sample_funcom_gpt.py ? I would greatly appreciate it.

**Comment by mcmillco** [comment]
We'll look into it right away.  Thanks for reporting.

**Comment by chiayisu** [comment]
sorrry. we forgot to change the command in README.md after we renamed the file. It's called sample_jam_cgpt.py instead of sample_funcom_gpt.py. We've changed it on README.md now. You can simply refer to the Inference section and copy the command for inference now.

**Comment by ying-hit** [comment]
> sorrry. we forgot to change the command in README.md after we renamed the file. It's called sample_jam_cgpt.py instead of sample_funcom_gpt.py. We've changed it on README.md now. You can simply refer to the Inference section and copy the command for inference now.

Thank you very much!
